# Generated by Django 5.2 on 2025-04-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_by',
        ),
    ]
